model_list:
  # Qwen3.5-35B
  - model_name: qwen3.5-35b
    litellm_params:
      model: custom_openai/qwen3.5-35b
      api_base: http://202.115.138.32:8011/v1
      api_key: sk-fc2e5f6697404812b099dad7f8a

  # Qwen3.8-Flash-Next
  - model_name: qwen3.8-flash-next
    litellm_params:
      model: custom_openai/qwen3.8-flash-next
      api_base: http://202.115.138.235:30002/v1
      api_key: sk-cdutwxc2026qwen3

  # DeepSeek V4 - 1
  - model_name: deepseek-v41-1
    litellm_params:
      model: custom_openai/deepseek-v41
      api_base: http://202.115.138.84:8026/v1

  # DeepSeek V4 - 2
  - model_name: deepseek-v41-2
    litellm_params:
      model: custom_openai/deepseek-v41
      api_base: http://202.115.138.86:8026/v1

  # bge-m3 embedding
  - model_name: bge-m3
    litellm_params:
      model: hosted_vllm/bge-m3
      api_base: http://202.115.138.34:8000/v1
      api_key: sk-cdutwxc2026bge
      
  # Auto Router
  - model_name: deepseek-v41-flash
    litellm_params:
      model: auto_router/complexity_router
      complexity_router_config:
        tiers:
          SIMPLE: ["deepseek-v41-1", "deepseek-v41-2"]
          MEDIUM: ["deepseek-v41-1", "deepseek-v41-2"]
          COMPLEXT: ["deepseek-v41-1", "deepseek-v41-2"]
          REASONING: ["deepseek-v41-1", "deepseek-v41-2"]
      complexity_router_default_model: deepseek-v41-1


litellm_settings:
  drop_params: true

  cache: true

  cache_params:
    type: redis
    host: litellm-redis
    port: 6379
    namespace: litellm
    ttl: 3600

  enable_redis_auth_cache: true

general_settings:
  user_api_key_cache_ttl: 300
  disable_env_credential_login: true
  master_key: os.environ/LITELLM_MASTER_KEY