model_list:

litellm_settings:
  drop_params: true

  cache: true

  cache_params:
    type: redis
    host: litellm-redis
    port: 6379
    namespace: litellm
    ttl: 3600

  enable_redis_auth_cache: true

general_settings:
  user_api_key_cache_ttl: 300